FROM ubuntu:16.04

LABEL maintainer="Jon D. (dArkjON), David B. (dalijolijo)"
LABEL version="0.15.2.0.0"

# Make ports available to the world outside this container
# DefaultPort = 8555
# RPCPort = 8556
# TorPort = 9051
# DEPRECATED: Use 'docker run -p 8555:8555 -p 8556:8556 -p 9051:9051 ...'
#EXPOSE 8555 8556 9051

USER root

# Change sh to bash
SHELL ["/bin/bash", "-c"]

# Define environment variable
ENV BTXPWD "bitcore"

RUN echo '*** BitCore BTX RPC Server ***'

#
# Creating bitcore user
#
RUN echo '*** Creating bitcore user ***' && \
    adduser --disabled-password --gecos "" bitcore && \
    usermod -a -G sudo,bitcore bitcore && \
    echo bitcore:$BTXPWD | chpasswd

#
# Running updates and installing required packages
#
RUN echo '*** Running updates and installing required packages ***' && \
    apt-get update && \
    apt-get dist-upgrade -y && \
    apt-get install -y  apt-utils \
                        autoconf \
                        automake \
                        autotools-dev \
                        build-essential \
                        bsdmainutils \
                        curl \
                        git \
                        libboost-all-dev \
                        libevent-dev \
                        libminiupnpc-dev \
                        libssl-dev \
                        libtool \
                        libzmq5-dev \
                        pkg-config \
                        software-properties-common \
                        sudo \
                        supervisor \
                        vim \
                        wget && \
    add-apt-repository -y ppa:bitcoin/bitcoin && \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y  libdb4.8-dev \
                        libdb4.8++-dev

#RUN apt-get install python-qt4 python-pip
RUN apt-get install -y libboost-program-options-dev
#RUN apt-get install libdb5.3++
RUN apt-get install -y libqrencode-dev
RUN apt-get install -y libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler


#
# Cloning and Compiling BitCore Wallet
#
RUN echo '*** Cloning and Compiling BitCore Wallet ***' && \
    cd && \
    echo "Execute a git clone of LIMXTEC/BitCore. Please wait..." && \
    git clone https://github.com/LIMXTEC/BitCore.git && \
    cd BitCore && \
    mkdir ./src/boost && \
    wget http://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.tar.gz && \
    tar xzf boost_1_58_0.tar.gz && \
    cd boost_1_58_0 && \
    ./bootstrap.sh --without-icu --prefix=../src/boost --with-libraries=chrono,filesystem,program_options,system,thread,test && \
    ./b2 --prefix=../src/boost link=static runtime-link=static threading=multi toolset=gcc release install
    
RUN cd .. && \
    ./autogen.sh && \
    ./configure --with-db4 --enable-tests=no --disable-hardening --disable-reduce-exports --enable-shared=no LDFLAGS=-L./src/boost/lib-static && \ 
    make && \
    cd && \
    cd BitCore/src && \
    strip bitcored && \
    cp bitcored /usr/local/bin && \
    strip bitcore-cli && \
    cp bitcore-cli /usr/local/bin && \
    chmod 775 /usr/local/bin/bitcore* && \
    cd 
#    rm -rf BitCore
#./configure --disable-dependency-tracking LDFLAGS=-static-libstdc++ 

#
# Configure bitcore.conf
#
COPY bitcore.conf /tmp
RUN echo '*** Configure bitcore.conf ***' && \
    chown bitcore:bitcore /tmp/bitcore.conf && \
    sudo -u bitcore mkdir -p /home/bitcore/.bitcore && \
    sudo -u bitcore cp /tmp/bitcore.conf /home/bitcore/.bitcore/bitcore.conf

#
# Copy Supervisor Configuration
#
COPY *.sv.conf /etc/supervisor/conf.d/

#
# Logging outside docker container
#
VOLUME /var/log

#
# Copy start script
#
RUN echo '*** Copy start script ***'
COPY start.sh /usr/local/bin/start.sh
RUN rm -f /var/log/access.log && mkfifo -m 0666 /var/log/access.log && \
    chmod 755 /usr/local/bin/*

ENV TERM linux
CMD ["/usr/local/bin/start.sh"]
#
# Configure bitcore.conf
#
COPY bitcore.conf /tmp
RUN echo '*** Configure bitcore.conf ***' && \
    chown bitcore:bitcore /tmp/bitcore.conf && \
    sudo -u bitcore mkdir -p /home/bitcore/.bitcore && \
    sudo -u bitcore cp /tmp/bitcore.conf /home/bitcore/.bitcore/bitcore.conf

#
# Copy Supervisor Configuration
#
COPY *.sv.conf /etc/supervisor/conf.d/

#
# Logging outside docker container
#
VOLUME /var/log

#
# Copy start script
#
RUN echo '*** Copy start script ***'
COPY start.sh /usr/local/bin/start.sh
RUN rm -f /var/log/access.log && mkfifo -m 0666 /var/log/access.log && \
    chmod 755 /usr/local/bin/*

ENV TERM linux
CMD ["/usr/local/bin/start.sh"]

